apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Home Server Dashboard
    favicon: https://gethomepage.dev/img/favicon.ico
    theme: dark
    color: slate
    headerStyle: boxed
    disableValidation: true
    layout:
      - Services:
          style: row
          columns: 3

  services.yaml: |
    - Services:
        - RustDesk:
            icon: rustdesk.png
            href: http://192.168.0.6:31116
            description: Self-hosted remote desktop

        - ArgoCD:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/argo-cd.pngs
            href: http://localhost:30001
            description: GitOps continuous delivery

  widgets.yaml: |
    - logo:
        icon: https://gethomepage.dev/img/logo.png

    - search:
        provider: google
        target: _blank

    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: short

  kubernetes.yaml: |
    mode: cluster

  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - icon: github.png
              href: https://github.com/thomasmathew365/Home-Server
        - Kubernetes Docs:
            - icon: kubernetes.png
              href: https://kubernetes.io/docs/

    - Media:
        - YouTube:
            - icon: youtube.png
              href: https://youtube.com

  docker.yaml: ""

  custom.css: ""

  custom.js: ""

  proxmox.yaml: ""
